number1 = int(input("عدد اول را وارد کنید : "))
number2 = int(input("عدد دوم را وارد کنید : "))
print(number1 + number2 )
print(number1 * number2)
print(number1 / number2)
print(number1 + number2 /2)
